# Generated by Django 6.0.1 on 2026-02-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
