# Generated by Django 6.0.1 on 2026-02-07 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_progress_document_status_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=255)),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('color', models.CharField(default='#ffff00', max_length=50)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.document')),
            ],
        ),
    ]
